# Numpy (Numerical Python)

In [1]:
import numpy as np

## 넘파이 배열 생성

In [ ]:
a1 = np.array([1, 2, 3]) # 리스트로 생성
a2 = np.array((1, 2, 3)) # 튜플로 생성
a3 = np.array([[1, 2, 3], [4, 5, 6]]) # 2차원 배열 생성
print(a3.transpose())
a4 = np.array([1, 2, 3], dtype=float) # 데이터 타입 지정
a5 = np.array([1, 2, 3], float) # 데이터 타입 지정 (축약형)
a6 = np.array([1, 4, 5, "8"]) # 문자열 포함 시 자동으로 문자열 배열로 변환
print(a6.dtype)
a7 = np.array([1, 4, 5, "8"], int) # 문자열을 포함해도 강제로 int 변환
a8 = np.arange(12).reshape(3,1,4) # 0~11숫자를 1행 4열짜리로 3개(면)
print(a8)

[[1 4]
 [2 5]
 [3 6]]
<U21
[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]


In [3]:
# 예외 상황: 크기가 다른 리스트 중첩 시 ValueError 발생 가능
test_list = [[1, 4, 5, 8], [1, 4, 5]]
# np.array(test_list, float)

## 넘파이 배열 속성 확인

In [ ]:
print(a1, type(a1), a1.dtype, a1.ndim, a1.shape, a1.size)

## 넘파이 배열 인덱싱

In [ ]:
# 1차원 배열 인덱싱
d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(d[0], d[1], d[2], d[-1], d[-2])

In [ ]:
# 2차원 배열 인덱싱
d2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(d2, type(d2), d2.dtype, d2.ndim, d2.shape, d2.size)
print(d2[0][0]) # 배열명[행][열]
print(d2[0, 0]) # 배열명[행, 열]
print(d2[1, 1])
print(d2[1, -1])

In [ ]:
# 3차원 배열 인덱싱 (면, 행, 열 순서)
d3 = np.arange(12).reshape(2, 2, 3)
print(d3)
print(d3[0][0][0])
print(d3[0, 0, 0])
print(d3[1, 1, 2])
print(d3[-1, -1, -1])

d[3] = 108
d2[1, 1] = 100
d3[1, 1, 1] = 1000
d2[0] = 50 # 0행 전체 변경
d3[0] = 50 # 0면 전체 변경
d3[1, 0] = 30 # 1면 0행 전체 변경
print(d3)

## 넘파이 배열 슬라이싱

In [ ]:
# 1차원 슬라이싱
d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(d[2:3], d[:], d[:-1])
print(d[::2], d[::-1]) # 간격 지정 및 역순

# 2차원 슬라이싱
d2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(d2[0])      # 행만 슬라이싱
print(d2[0, :])   # 행의 전체 열 슬라이싱
print(d2[:, :-1]) # 마지막 열 제외한 전체 행/열 슬라이싱
print(d2[::2, ::2]) # 2행 2열 간격 슬라이싱

In [ ]:
d2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
d2[::2, ::3] = 30 # 슬라이싱된 요소값 변경
d2[:, :] = -1    # 전체 요소값 변경
# 일반 리스트는 오류남. 슬라이싱한 크기와 같은 리스트로 지정해줘야됨.

[[30  2  3 30  5]
 [ 6  7  8  9 10]]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


## 불 인덱싱

In [13]:
data = np.array([4, 6, 7, 3, 2, 0])
print(data[data > 3]) # 조건을 만족하는 요소만 추출
print(data > 3)       # True/False 배열 반환

# 불리언 리스트를 인덱스로 사용
cond = [False, True, True, False, False, True]
print(data[cond])

# 복합 조건 및 함수 활용
print(data[(data > 3) & (data < 6)]) # AND 조건
print(data[data % 2 == 0])           # 짝수만 추출
print(data[data < data.mean()])      # 평균보다 작은 값 추출

[4 6 7]
[ True  True  True False False False]
[6 7 0]
[4]
[4 6 2 0]
[3 2 0]


## 팬시 인덱싱

In [18]:
# 1차원 배열 팬시 인덱싱
f = np.array([4, 6, 7, 3, 2])
indexes = np.array([1, 2, 0, 2, 2, 2])
print(f[indexes])
# 2차원 배열 팬시 인덱싱
f2 = np.array([[1, 4], [9, 16]])
x = np.array([0, 1, 1, 1, 0, 0])
y = np.array([0, 0, 0, 1, 1, 1])
print(f2[x,y])

[6 7 4 7 7 7]
[ 1  9  9 16  4  4]


## 정렬

In [ ]:
numbers = np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
sorted_numbers = np.sort(numbers)
print(numbers)
print(sorted_numbers)
# 기본적으로 퀵솔트 방식(메모리 덜 쓰기 위해)
# 내림차순 정렬 (슬라이싱 활용)
print(sorted_numbers[::-1])

# 원본 배열 직접 정렬
numbers.sort()
print(numbers)

[2 8 9 7 3 1 4 5 6]
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[1 2 3 4 5 6 7 8 9]


In [31]:
# 2차원 배열 정렬
arr2d = np.array([[5, 6, 7, 8], [4, 3, 2, 1], [10, 9, 12, 11]])
print(np.sort(arr2d)) # 기본 axis=1 (열 방향)
print(np.sort(arr2d, axis=0)) # 행 방향 정렬

# 정렬된 인덱스 반환 (argsort)
numbers = np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
sorted_indexes = np.argsort(numbers)
print(sorted_indexes)

# 연습문제 데이터
names = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
print(np.sort(names))
scores = np.array([78, 95, 84, 98, 88])
scores.sort()
print(scores)

[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]
[5 0 4 6 7 8 3 1 2]
['John' 'Kate' 'Mike' 'Samuel' 'Sarah']
[78 84 88 95 98]


## 사칙연산 및 브로드캐스팅

In [32]:
x = np.arange(1, 7).reshape(2, 3)
print(x + x) # 동일 구조 요소별 연산
print(x + 2) # 스칼라 브로드캐스팅

y = np.array([10, 20, 30])
print(x + y) # 다른 구조 배열 간 브로드캐스팅

[[ 2  4  6]
 [ 8 10 12]]
[[3 4 5]
 [6 7 8]]
[[11 22 33]
 [14 25 36]]


In [ ]:
ndarray = np.arange(12).reshape(2,2,3)
# axis = 0,1,2 -> 면,행,렬
a = ndarray.sum(axis=2)
a = ndarray.mean(axis=2)
ndarray.max(axis=None) 
ndarray.min(axis=None) 
a = ndarray.argmax(axis=None) # 최대값의 인덱스
print(a)
ndarray.argmin(axis=None) # 최소값의 인덱스
print(ndarray.all(axis=None)) # 모든 요소가 참인지 확인
ndarray.any(axis=None) # 하나라도 참인지 확인

11
False


np.True_

In [63]:
# 조건 확인
a = np.array([[1,2,3],[4,5,6]])
print(np.all(a > 3))
print(np.any(a > 4))

# 1. 배열 내 결측치(NaN) 포함 여부 확인
data = np.array([1, 2, np.nan, 4])
print(np.any(np.isnan(data))) # 하나라도 NaN이면 True

# 2. 두 배열의 완전 일치 여부 확인
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
print(np.all(arr1 == arr2)) # 모든 요소가 같으면 True
a1 = [1,2,3]
a2 = [1,2,3]
print(a1==a2)
print(arr1==arr2)

False
True
True
True
True
[ True  True  True]
